### ISSUE TITLE
Fix Federated Instances

### ISSUE THREAD

**Issue by maltfield** [maltfield/awesome-lemmy-instances#30]
This ticket will track the effort to update this repo to query the new `federated-instances` endpoint ,which was segregated in v0.18.0

 * https://github.com/LemmyNet/lemmy/issues/1931
 * https://github.com/LemmyNet/lemmy/pull/2813

See example of the failure this causes

 * https://github.com/maltfield/awesome-lemmy-instances/actions/runs/5402890661/jobs/9814868143

```
2023-06-28T15:24:56.6362683Z + head --bytes 1024 uptime.json
2023-06-28T15:24:56.6362999Z 0 uptime.json
2023-06-28T15:24:56.6370748Z + tail --bytes 1024 uptime.json
2023-06-28T15:24:56.6381190Z + exit 0
2023-06-28T15:24:57.6042573Z {"data":{"nodes":[{"domain":"lemmy.bitgoblin.tech","uptime_alltime":"100.00"},{"domain":"lemmy.axiom-labs.dev","uptime_alltime":"33.80"},{"domain":"rekabu.ru","uptime_alltime":"100.00"},{"domain":"pwzle.com","uptime_alltime":"34.78"},{"domain":"lemmy.roflblog.net","uptime_alltime":"9.75"},{"domain":"fed.creve.com","uptime_alltime":"100.00"},{"domain":"lemmy.soulfly.dk","uptime_alltime":"100.00"},{"domain":"lemmy.flunky.club","uptime_alltime":"100.00"},{"domain":"lemmy.fosshost.com","uptime_alltime":"100.00"},{"domain":"lemmy.shwizard.chat","uptime_alltime":"100.00"},{"domain":"lemmy.robotra.sh","uptime_alltime":"100.00"},{"domain":"clipbored.xyz","uptime_alltime":"100.00"},{"domain":"lemmy.starlightkel.xyz","uptime_alltime":"99.41"},{"domain":"feddit.dnico.io","uptime_alltime":"100.00"},{"domain":"l.lucitt.com","uptime_alltime":"100.00"},{"domain":"lemmy.science.social","uptime_alltime":"100.00"},{"domain":"sub.wetshaving.social","uptime_alltime":"97.84"},{"domain":"campfyre.nickwebster.dev","uptime_alltime":":"99.81"},{"domain":"lemmy.thebitpros.com","uptime_alltime":"46.70"},{"domain":"millenium.red","uptime_alltime":"70.67"},{"domain":"lemmy.schuerz.at","uptime_alltime":"99.58"},{"domain":"granitestate.social","uptime_alltime":"99.55"},{"domain":"lemmy.kaouenn-noz.fr","uptime_alltime":"0.00"},{"domain":"exploding-heads.com","uptime_alltime":"99.36"},{"domain":"lemmy.rollenspiel.monster","uptime_alltime":"99.66"},{"domain":"baraza.africa","uptime_alltime":"98.81"},{"domain":"cyber-news.fr","uptime_alltime":"85.73"},{"domain":"collapse.cat","uptime_alltime":"98.08"},{"domain":"lemmy.blahaj.zone","uptime_alltime":"98.16"},{"domain":"linkage.ds8.zone","uptime_alltime":"98.01"},{"domain":"links.roobre.es","uptime_alltime":"99.72"},{"domain":"ds9.lemmy.ml","uptime_alltime":"96.56"},{"domain":"stammtisch.hallertau.social","uptime_alltime":"99.22"},{"domain":"lemmy.darcy.social","uptime_alltime":"73.52"},{"domain":"lemmy.tedomum.net","uptime_alltime":"99.78"},{"domain":"forum.nobigtech.es","uptime_alltime":"82.13"}]}}/home/runner/work/awesome-lemmy-instances/awesome-lemmy-instances
2023-06-28T15:24:57.6047585Z /home/runner/work/awesome-lemmy-instances/awesome-lemmy-instances
2023-06-28T15:24:57.6050015Z ['README.md', 'get-uptime.sh', 'stats-crawler.sh', 'generate_readme.py', 'push.sh', 'uptime.json', 'lemmy-migration-find-subreddits-communities.jpg', 'LICENSE', '.gitignore', '.git', '.github', 'awesome-lemmy-instances.csv', 'lemmy-stats-crawler']
2023-06-28T15:24:57.6052571Z ['README.md', 'target', 'Cargo.lock', 'Cargo.toml', 'src', 'LICENSE', '.gitignore', '.git', '.woodpecker.yml', 'lemmy-stats-crawler.json']
2023-06-28T15:24:57.6506776Z Traceback (most recent call last):
2023-06-28T15:24:57.6508371Z   File "/home/runner/work/awesome-lemmy-instances/awesome-lemmy-instances/./generate_readme.py", line 109, in <module>
2023-06-28T15:24:57.6509772Z     instances_with_blocked = [x for x in data['instance_details'] if x['site_info']['federated_instances'] != None ]
2023-06-28T15:24:57.6511124Z   File "/home/runner/work/awesome-lemmy-instances/awesome-lemmy-instances/./generate_readme.py", line 109, in <listcomp>
2023-06-28T15:24:57.6512426Z     instances_with_blocked = [x for x in data['instance_details'] if x['site_info']['federated_instances'] != None ]
2023-06-28T15:24:57.6513282Z KeyError: 'federated_instances'
2023-06-28T15:24:57.7478937Z ##[error]Process completed with exit code 1.
```

**Comment by maltfield** [comment]
Previously this information was provided by `lemmy-stats-crawler` in the json that queried the "site" endpoint:

* https://lemmy.ml/api/v3/site

Now, as of v0.18.0, it appears to be in this endpoint

 * https://lemmy.ml/api/v3/federated_instances

**Comment by maltfield** [comment]
I also created a ticket upstream so that this data is still returned by `lemmy-stats-crawler`. I think it's important stats data that is now missing..

 * https://github.com/LemmyNet/lemmy-stats-crawler/issues/12

**Comment by maltfield** [comment]
I discovered that `federated_instances` *is* still available from `lemmy-stats-crawler` -- it just moved. See changes for the new path here:

 * https://github.com/maltfield/awesome-lemmy-instances/commit/a33001d1aa88f1fea42068d570b0f63d7933a24a#diff-106145ac9810231865388dcefdc99cdcb0a69d1b45ed55df408c5bc955420dd7R123-R130
