### ISSUE TITLE
Prevent Occassional GitHub Actions Errors

### ISSUE THREAD

**Issue by maltfield** [maltfield/awesome-lemmy-instances#39]
A few times per day the hourly updates have been failing. Unfortunately I can't always see why because the log output gets truncated due to the `lemmy-stats-crawler` debug output.

I did manage to find one with a traceback

 * https://github.com/maltfield/awesome-lemmy-instances/actions/runs/5909946832/job/16031040941

```
2023-08-19T06:34:24.0560176Z Traceback (most recent call last):
2023-08-19T06:34:24.0564873Z   File "/home/runner/work/awesome-lemmy-instances/awesome-lemmy-instances/./generate_readme.py", line 114, in <module>
2023-08-19T06:34:24.0565728Z     instances_with_blocked = [x for x in data['instance_details'] if x['federated_instances']['federated_instances']['blocked'] != [] ]
2023-08-19T06:34:24.0567287Z   File "/home/runner/work/awesome-lemmy-instances/awesome-lemmy-instances/./generate_readme.py", line 114, in <listcomp>
2023-08-19T06:34:24.0568374Z     instances_with_blocked = [x for x in data['instance_details'] if x['federated_instances']['federated_instances']['blocked'] != [] ]
2023-08-19T06:34:24.0569114Z KeyError: 'federated_instances'
2023-08-19T06:34:25.0501530Z ##[error]Process completed with exit code 1.
```

**Comment by maltfield** [comment]
My latest commit reduced the verbosity from 4 to 1 of `lemmy-stats-crawler` (which doesn't appear to be failing but causes the logs to truncate), so if it keeps failing then hopefully I'll be able to see why.
